resources:
- name: pcf-pipelines
  type: git
  source:
    uri: ((git_repo)) 
    branch: ((git_branch))
    skip_ssl_verification: true
- name: release
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release


jobs:
- name: deploy-turbulence
  plan:
  - get: pcf-pipelines
  - get: release
  - task: upload-release 
    file: pcf-pipelines/tasks/upload-bosh-release/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USER: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
  - task: deploy-turbulence
    file: pcf-pipelines/tasks/deploy-turbulence/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
      OPSMAN_USER: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      TURBULENCE_API_IP: ((turbulence_api_ip))
