---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  PRODUCT_NAME:
  PRODUCT_PROPERTIES:
  RESOURCE_CONFIG:
  NETWORK_PROPERTIES:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-product/task.sh
