---
platform: linux

image_resource:
  type: docker-image
  source: { repository: golang, tag: "1.7"}

run:
  path: pcf-pipelines/tasks/chaos-loris/build-service-broker.sh

inputs:
- name: pcf-pipelines 
- name: service-broker-repo

outputs:
- name: binary
