---
platform: linux

image_resource:
  type: docker-image
  source: {repository: smatyukevich/docker-cfbosh}

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/deploy-rmq-broker/task.sh
