---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/chaos-loris-build
    tag: v1.1

run:
  path: pcf-pipelines/tasks/mongo-broker/build.sh

inputs:
- name: pcf-pipelines 
- name: broker-repo
outputs:
- name: binary
