resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:tosin2013/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

- name: pivnet-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: p-spring-cloud-services
    product_version: {{p_spring_cloud_services_version}}
    sort_by: semver

jobs:
- name: upload-tile
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      trigger: true
      params:
        globs:
        - "*pivotal"

  - task: upload-tile-and-stemcell
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: {{iaas_type}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: ""
      OM_IP: ""

  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      PRODUCT_NAME: p-spring-cloud-services
      DEPENDENCY_PRODUCT_TILES: ((dependency_product_tiles))

- name: configure-product-install
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [upload-tile]

  - task: configure-product
    file: pcf-pipelines/tasks/configure-product-install/task.yml
    params:
      PRODUCT_NAME: p-spring-cloud-services
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USER: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      PRODUCT_PROPERTIES: {{product-properties}}
      RESOURCE_CONFIG: {{resource-config}}
      NETWORK_PROPERTIES: {{network-properties}}

- name: product-apply-changes
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [configure-product-install]

  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
