---
platform: linux

image_resource:
  type: docker-image
  source: {repository: smatyukevich/docker-cfbosh}

inputs:
  - name: pcf-pipelines
  - name: release 

run:
  path: pcf-pipelines/tasks/upload-bosh-release/task.sh
